### PR TITLE
Template stuff

### LINKED ISSUE #5: Generate friendly HTML Skeleton
Create an HTML skeleton template.
Define variables which will be populated by received user data later.
Use the templating engine Thymeleaf.

### PR DESCRIPTION
**Pull request by mariusbegby**
Added html template.

Input payload:
```json
{
    "personaliaSegment": {
        "firstName": "John",
        "lastName": "Doe",
        "email": "johndoe@example.com",
        "phone": "12345678",
        "dateOfBirth": "2022-10-31T23:00:00.000Z",
        "gender": "Male",
        "address": "Streetname 123",
        "address2": "",
        "zipCode": "1234",
        "city": "New york",
        "country": "United States",
        "summary": "I am a cool guy.",
        "profilePicture": null
    },
    "educationSegment": {
        "educationList": [
            {
                "school": "School of Technology",
                "degree": "Pro programmer",
                "startDate": "2024-02-29T23:00:00.000Z",
                "endDate": "2024-08-31T22:00:00.000Z",
                "isStudying": false
            }
        ]
    },
    "experienceSegment": {
        "experienceList": [
            {
                "company": "Best Company",
                "position": "Pro Developer",
                "startDate": "2024-08-31T22:00:00.000Z",
                "endDate": "2024-09-10T16:19:37.257Z",
                "isWorking": true,
                "description": "Worked on coding and stuff"
            }
        ]
    },
    "skillsSegment": {
        "input": "",
        "skillList": [
            {
                "skill": "programming"
            },
            {
                "skill": "coding"
            }
        ]
    },
    "certificationsSegment": {
        "certificationList": [
            {
                "name": "Certified Pro",
                "issuer": "Myself",
                "startDate": "2024-08-31T22:00:00.000Z",
                "endDate": "2024-09-01T22:00:00.000Z",
                "isNotExpiring": true
            }
        ]
    },
    "coursesSegment": {
        "courseList": [
            {
                "name": "How to program",
                "instructor": "YouTube",
                "completionDate": "2024-09-10T16:19:37.257Z",
                "duration": "Hours"
            }
        ]
    }
}
```

Output PDF 
[example_cv.pdf](https://github.com/user-attachments/files/16949994/example_cv.pdf)

### CODE REVIEW

**Review by jacobg431 — CHANGES_REQUESTED** [review]
Good job, but mind the language. Two commits contain inappropriate words.

**Comment by mariusbegby** [comment]
cancel me

**Comment by mariusbegby** [comment]
> Good job, but mind the language. Two commits contain inappropriate words.

What changes do you want?

**Comment by jacobg431** [comment]
Please change the names of commits 382761c and 7cfac2c

**Pull request closed without merging**
